name: Gradle Release

on:
  workflow_call:
    inputs:
      type:
        description: 'Release type'
        required: true
        type: string

jobs:
  release:
    name: gradle release
    runs-on: ubuntu-latest
    steps:
      - name: Validate 'Release Type' param
        id: validate_type
        env:
          TYPE: ${{ inputs.type }}
        run: |
          valid_types=(major minor patch)
          if [[ ! ${valid_types[*]} =~ "$TYPE" ]]; then
            echo "Unknown release type: $TYPE"
            exit 1
          fi
      - name: Checkout project sources ('main' branch)
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0

      - name: Get current version
        id: get_version
        run: |
          source gradle.properties
          echo "current_version=${version}" >> $GITHUB_ENV

      - name: Determine version type
        id: bump_version
        env:
          TYPE: ${{ inputs.type }}
          VERSION: ${{ env.current_version }}
        run: |
          export major=$(echo "${VERSION}" | cut -d. -f1)
          export minor=$(echo "${VERSION}" | cut -d. -f2)
          export patch=$(echo "${VERSION}" | cut -d. -f3 | cut -d- -f1)
          echo "resolved: ${major}.${minor}.${patch}"
          
          if [[ "$TYPE" == "major" ]]; then
            echo "new_version=$((major+1)).0.0" >> $GITHUB_ENV
            echo "new_snapshot_version=$((major+1)).0.1-SNAPSHOT" >> $GITHUB_ENV
          elif [ "$TYPE" == "minor" ]; then
            echo "new_version=${major}.$((minor+1)).0" >> $GITHUB_ENV
            echo "new_snapshot_version=${major}.$((minor+1)).1-SNAPSHOT" >> $GITHUB_ENV
          else
            echo "new_version=${major}.${minor}.${patch}" >> $GITHUB_ENV
            echo "new_snapshot_version=${major}.${minor}.$((patch+1))-SNAPSHOT" >> $GITHUB_ENV
          fi
      - name: Set git config 'user.name' and 'user.email'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Run 'gradle release'
        id: gradle_release
        run: |
          echo "Type: ${{ inputs.type }}"
          echo "Current version: ${{ env.current_version }}"
          echo "New version: ${{ env.new_version }}"
          echo "New snapshot version: ${{ env.new_snapshot_version }}"
          echo "./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ env.new_version }} -Prelease.newVersion=${{ env.new_snapshot_version }}"
          gradle release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ env.new_version }} -Prelease.newVersion=${{ env.new_snapshot_version }}
