name: Gradle Build + intTests

on:
  workflow_call:

jobs:
  intTest:
    name: gradle intTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0
        with:
          cache-read-only: true

      - name: Run integration tests
        run: ./gradlew intTest -x test --no-daemon

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/intTest/TEST-*.xml'
